substitutions:
  name: shelly-plus-1pm-mini-tv-room
  device_name: Shelly Plus 1PM Mini (TV room)

<<: !include templates/shelly-plus-1pm-mini.yaml

light:
  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    name: "Bracket Lamp"
    output: relay_output