substitutions:
  device_name: "Shelly Plus 1 Mini (reduit fan)"
  name: shelly-plus-1-mini-reduit-fan

  ## FAN DELAY
  additional_delay_on_integer: "3" # additional ON delay in seconds, can be changed if needed by front-end
  factory_delay_on: 0s     # factory ON delay in timestamp, cannot be changed
  additional_delay_off_integer: "6" # additional OFF delay in seconds, can be changed if needed by front-end
  factory_delay_off: 0s    # factory OFF delay in timestamp, cannot be changed

packages:
  common: !include fan_common.yaml